In [1]:
import altair as alt
import pandas as pd
import numpy as np

# Datensatz laden
source_file = "Corona_Zahlen_Kantone/COVID19_Fallzahlen_Kanton_BE_total.csv"
data_source = pd.DataFrame(pd.read_csv(source_file))
data_source

,date,time,abbreviation_canton_and_fl,ncumul_tested,ncumul_conf,new_hosp,current_hosp,current_icu,current_vent,ncumul_released,ncumul_deceased,source,current_isolated,current_quarantined,current_quarantined_riskareatravel
0,2020-02-27,NaN,BE,NaN,1.0,NaN,NaN,NaN,NaN,NaN,0.0,https://covid-kennzahlen.apps.be.ch/,NaN,NaN,NaN
1,2020-02-28,NaN,BE,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,https://www.be.ch/portal/de/index/mediencenter...,NaN,NaN,NaN
2,2020-02-29,NaN,BE,NaN,2.0,NaN,NaN,NaN,NaN,NaN,0.0,https://covid-kennzahlen.apps.be.ch/,NaN,NaN,NaN
3,2020-03-01,NaN,BE,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,https://www.be.ch/portal/de/index/mediencenter...,NaN,NaN,NaN
4,2020-03-02,NaN,BE,NaN,6.0,NaN,NaN,NaN,NaN,NaN,0.0,https://covid-kennzahlen.apps.be.ch/,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,2022-03-27,NaN,BE,NaN,390991.0,NaN,NaN,NaN,NaN,NaN,1513.0,https://covid-kennzahlen.apps.be.ch/,7613.0,0.0,NaN
757,2022-03-28,NaN,BE,NaN,393287.0,NaN,261.0,25.0,17.0,NaN,1514.0,https://covid-kennzahlen.apps.be.ch/,6812.0,0.0,NaN
758,2022-03-29,NaN,BE,NaN,394953.0,NaN,261.0,25.0,17.0,NaN,1515.0,https://covid-kennzahlen.apps.be.ch/,7015.0,0.0,NaN
759,2022-03-30,NaN,BE,NaN,395974.0,NaN,253.0,22.0,15.0,NaN,1515.0,https://covid-kennzahlen.apps.be.ch/,NaN,NaN,NaN
760,2022-03-31,NaN,BE,NaN,395976.0,NaN,253.0,22.0,15.0,NaN,1515.0,https://covid-kennzahlen.apps.be.ch/,NaN,NaN,NaN

In [2]:
data = data_source[["date", "abbreviation_canton_and_fl", "ncumul_conf", "current_hosp", "ncumul_deceased"]]
data["month"] = pd.to_datetime(data["date"]).dt.month
data

/var/folders/s1/90kv3cpx61v31kb62y63wm2c0000gn/T/ipykernel_88521/1036907155.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["month"] = pd.to_datetime(data["date"]).dt.month

,date,abbreviation_canton_and_fl,ncumul_conf,current_hosp,ncumul_deceased,month
0,2020-02-27,BE,1.0,NaN,0.0,2
1,2020-02-28,BE,1.0,NaN,NaN,2
2,2020-02-29,BE,2.0,NaN,0.0,2
3,2020-03-01,BE,2.0,NaN,NaN,3
4,2020-03-02,BE,6.0,NaN,0.0,3
...,...,...,...,...,...,...
756,2022-03-27,BE,390991.0,NaN,1513.0,3
757,2022-03-28,BE,393287.0,261.0,1514.0,3
758,2022-03-29,BE,394953.0,261.0,1515.0,3
759,2022-03-30,BE,395974.0,253.0,1515.0,3
760,2022-03-31,BE,395976.0,253.0,1515.0,3

In [ ]:
ticks = ["2020-02-25", "2020-02-28", "2020-03-16", "2020-04-27", "2020-05-11", "2020-07-06", "2020-10-19","2020-12-23", "2021-01-18", "2021-03-01", "2021-09-13", "2021-12-20", "2022-02-17"]

lines = alt.Chart(data).mark_line(color="green").encode(
    x=alt.X('date:T',axis=alt.Axis(title="Datum", format="%d.%m.%y", values=ticks, labelAngle=-50, labelOverlap=False, labelFontSize=10)),
    y=alt.Y('current_hosp', title="Hospitalisierungen", scale=alt.Scale(domain=[0, 450]))
).properties(
    width="container",
    height=400
)
lines

alt.Chart(...)

In [4]:
lines.to_json()
with open("Hosp_BE.json", "w") as f:
    f.write(lines.to_json())